/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlykhachsan.*;
import quanlykhachsan.dao.*;
import quanlykhachsan.entity.*;
/**
 *
 * @author Phung
 */
public class DSPhongFrame extends javax.swing.JFrame {

    /**
     * Creates new form DSPhongFrame
     */
    DefaultTableModel modeltable;
    DefaultComboBoxModel modelCombox;
     DefaultComboBoxModel modelComboxLP;
    PhongDao pDao = new PhongDao();
    LoaiPhongDao lpDao = new LoaiPhongDao();
    public DSPhongFrame() {
        initComponents();
         ImagePanel panel = new ImagePanel(new ImageIcon("D:/LegendSoft/Images/bg7.jpg").getImage());
        getContentPane().add(panel);
        
        ImageIcon iconExit = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/exit2.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnExit.setIcon(iconExit);
        
        ImageIcon iconThue = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/key.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnThue.setIcon(iconThue);
        
        ImageIcon iconTra = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/exit4.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnTra.setIcon(iconTra);
        
        ImageIcon iconTim = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/search.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnTim.setIcon(iconTim);
        
        ImageIcon iconAdd= new ImageIcon(new ImageIcon("D:/LegendSoft/Images/add4.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnAdd.setIcon(iconAdd);
        
        ImageIcon iconEdit= new ImageIcon(new ImageIcon("D:/LegendSoft/Images/edit.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnEdit.setIcon(iconEdit);
        
        ImageIcon iconDelete= new ImageIcon(new ImageIcon("D:/LegendSoft/Images/delete4.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnDelete.setIcon(iconDelete);
        
         String [] ColumNames={"STT","Phòng","Loại Phòng", "Đơn Giá", "Tình trạng"}; 
        modeltable = new DefaultTableModel(null , ColumNames);
        
        List<Phong> pTList = pDao.getPhongList();
        hienThiDsPhong(pTList);
        
       modelCombox = (DefaultComboBoxModel) cmbLoaiPhongTim.getModel();
       List<Loaiphong> lpListTim = lpDao.getLoaiPhongList();
       hienthidsloaipTim(lpListTim);
       
        modelComboxLP = (DefaultComboBoxModel) cmbLoaiPhong.getModel();
       List<Loaiphong> lpList = lpDao.getLoaiPhongList();
       hienthidsloaip(lpList);
       
       this.cmbLoaiPhong.setSelectedIndex(0);
       this.cmbLoaiPhongTim.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnTra = new javax.swing.JButton();
        btnThue = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        cmbLoaiPhongTim = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbLoaiPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtTenPhongTim = new javax.swing.JTextField();
        cbLoaiPhong = new javax.swing.JCheckBox();
        cbTenPhong = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh sách tất cả các phòng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTra.setText("Trả");
        btnTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraMouseClicked(evt);
            }
        });

        btnThue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThueMouseClicked(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimMouseClicked(evt);
            }
        });

        cmbLoaiPhongTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbLoaiPhongTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Tìm phòng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên phòng");

        txtTenPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Loại phòng");

        cmbLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(cmbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGhiChu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cmbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        txtTenPhongTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        cbLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbLoaiPhong.setForeground(new java.awt.Color(51, 51, 51));
        cbLoaiPhong.setText("Tên Loại Phòng");

        cbTenPhong.setBackground(new java.awt.Color(255, 255, 255));
        cbTenPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTenPhong.setText("Tên phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(cbTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTenPhongTim, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbLoaiPhongTim, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenPhongTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLoaiPhongTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoaiPhong)
                            .addComponent(cbTenPhong))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThueMouseClicked
        // TODO add your handling code here:
        ThueFrame room = new ThueFrame();
        room.setVisible(true);
        room.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnThueMouseClicked

    private void btnTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTraMouseClicked
        // TODO add your handling code here:
        DSPhongThue room = new DSPhongThue();
        room.setVisible(true);
         room.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnTraMouseClicked

    private void btnTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimMouseClicked
        // TODO add your handling code here:
         List<Phong> pTList = null; 
        boolean kt = true;
        if(cbTenPhong.isSelected() == false && this.cbLoaiPhong.isSelected() == false)
        {
            JOptionPane.showConfirmDialog((Component) null, "Vui lòng check tên hay loại phòng  muốn tìm", "Thông báo", JOptionPane.CLOSED_OPTION);
            kt = false;
            loadDSPhong();
        }
        else
        {
            Loaiphong lps = (Loaiphong) this.cmbLoaiPhongTim.getSelectedItem();
            if(this.cbTenPhong.isSelected() && this.txtTenPhongTim.getText() != "" && this.cbLoaiPhong.isSelected())
            {
                pTList = pDao.timPhongTrongByLoaiTen(txtTenPhongTim.getText(), lps.getMaLoai());
            }
            else
            {
                if(this.cbTenPhong.isSelected() && this.txtTenPhongTim.getText() != "")
                {
                    pTList = pDao.timPhongTrongByTen(txtTenPhongTim.getText());
                }
                else
                {
                    if(this.cbLoaiPhong.isSelected())
                    {
                        
                        pTList = pDao.timPhongTrongByLoai(lps.getMaLoai());
                    }
                    else
                    {
                         JOptionPane.showConfirmDialog((Component) null,  "Vui lòng check tên hay loại phòng muốn tìm", "Thông báo", JOptionPane.CLOSED_OPTION);
                         kt = false;
                    }
                }
                
            }
        }
        if(kt == true)
        {
            if(pTList == null || pTList.isEmpty())
            {
                JOptionPane.showConfirmDialog((Component) null, "Tên hoặc loại phòng không có", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
            else
            {
                hienThiDsPhong(pTList);
            }
        }
    }//GEN-LAST:event_btnTimMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        boolean kq = false;
        if(!this.txtTenPhong.getText().equals("") && this.cmbLoaiPhong.getSelectedIndex()!= -1)
        {
            List <Phong> ktp = pDao.timPhongByTen(this.txtTenPhong.getText());
            if(ktp == null || ktp.isEmpty())
            {
                Loaiphong lp = (Loaiphong) this.cmbLoaiPhong.getSelectedItem();
                Phong pThem = new Phong(this.txtTenPhong.getText(),this.txtGhiChu.getText(),"Trong",lp.getMaLoai());
                kq = pDao.themPhong(pThem);
            }
            else
            {
                JOptionPane.showConfirmDialog((Component) null, "Tên phòng này đã có rồi!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
        }
         else
        {
            JOptionPane.showConfirmDialog((Component) null, "Vui lòng điền tên phòng!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        if(kq == true)
        {
             JOptionPane.showConfirmDialog((Component) null, "Đã thêm phòng thành công ^.^", "Thông báo", JOptionPane.CLOSED_OPTION);
             loadDSPhong();
        }
        else
        {
             JOptionPane.showConfirmDialog((Component) null, "Không thêm được phòng T.T", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
         boolean kq = false;
        if(!this.txtTenPhong.getText().equals("") && this.cmbLoaiPhong.getSelectedIndex()!= -1)
        {
            List <Phong> ktp = pDao.timPhongByTen(this.txtTenPhong.getText());
            if(ktp == null || ktp.isEmpty())
            {
                  JOptionPane.showConfirmDialog((Component) null, "Tên phòng này chưa có, không thể sửa!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
            else
            {
                Loaiphong lp = (Loaiphong) this.cmbLoaiPhong.getSelectedItem();
                ktp.get(0).setMaLoai(lp.getMaLoai());
                ktp.get(0).setGhiChu(this.txtGhiChu.getText());
                kq = pDao.suaPhong(ktp.get(0));
            }
        }
         else
        {
            JOptionPane.showConfirmDialog((Component) null, "Vui lòng điền tên phòng!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        if(kq == true)
        {
             JOptionPane.showConfirmDialog((Component) null, "Đã sửa phòng thành công ^.^", "Thông báo", JOptionPane.CLOSED_OPTION);
             loadDSPhong();
        }
        else
        {
             JOptionPane.showConfirmDialog((Component) null, "Không sửa được phòng T.T", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
      /*   boolean kq = false;
        if(!this.txtTenPhong.getText().equals("") && this.cmbLoaiPhong.getSelectedIndex()!= -1)
        {
            List <Phong> ktp = pDao.timPhongByTen(this.txtTenPhong.getText());
            if(ktp == null || ktp.isEmpty())
            {
                  JOptionPane.showConfirmDialog((Component) null, "Tên phòng này chưa có, không thể xóa!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
            else
            {
                Loaiphong lp = (Loaiphong) this.cmbLoaiPhong.getSelectedItem();
                kq = pDao.xoaPhong(ktp.get(0));
            }
        }
         else
        {
            JOptionPane.showConfirmDialog((Component) null, "Vui lòng điền tên phòng!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        if(kq == true)
        {
             JOptionPane.showConfirmDialog((Component) null, "Đã sửa phòng thành công ^.^", "Thông báo", JOptionPane.CLOSED_OPTION);
             loadDSPhong();
        }
        else
        {
             JOptionPane.showConfirmDialog((Component) null, "Không sửa được phòng T.T", "Thông báo", JOptionPane.CLOSED_OPTION);
        }*/
    }//GEN-LAST:event_btnDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSPhongFrame().setVisible(true);
            }
        });
    }
    
    void hienthidsloaip(List <Loaiphong> dsloaip) {

        modelComboxLP.removeAllElements();
        for (int i = 0; i < dsloaip.size(); i++) {
            Loaiphong a = (Loaiphong) dsloaip.get(i);
            modelComboxLP.addElement(a);

        }
    }
    
    void hienthidsloaipTim(List <Loaiphong> dsloaip) {

        modelCombox.removeAllElements();
        for (int i = 0; i < dsloaip.size(); i++) {
            Loaiphong a = (Loaiphong) dsloaip.get(i);
            modelCombox.addElement(a);

        }
    }
    
    void loadDSPhong()
    {
        List<Phong> pTList = pDao.getPhongList();
        hienThiDsPhong(pTList);
    }
    void hienThiDsPhong(List <Phong> dsp)
    {  
        modeltable.getDataVector().removeAllElements();
       // modeltable.fireTableDataChanged(); 
       LoaiPhongDao lpDao = new LoaiPhongDao();
       for(int i=0;i<dsp.size();i++)
        {     
            Phong s = (Phong) dsp.get(i);
            Loaiphong lp = lpDao.TonTai(s.getMaLoai());
          // if(s.getTinhTrang().equals("Trong"))
           // {
                Object[] items = new Object[]{i+1,s.getTenPhong(), lp.getTenLoai(), lp.getDonGia(), s.getTinhTrang(), s.getGhiChu()};
                modeltable.addRow(items);
            //}
        }
        jTable1.setModel(modeltable);
        jTable1.setRowHeight(30);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTra;
    private javax.swing.JCheckBox cbLoaiPhong;
    private javax.swing.JCheckBox cbTenPhong;
    private javax.swing.JComboBox<String> cmbLoaiPhong;
    private javax.swing.JComboBox<String> cmbLoaiPhongTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTenPhongTim;
    // End of variables declaration//GEN-END:variables
}
