package quanlykhachsan.entity;
// Generated Jun 1, 2019 12:10:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private Integer maCthd;
     private int maHd;
     private int maPhong;
     private Integer soNgayThue;
     private Float donGia;
     private Date ngayTao;

    public Chitiethoadon() {
    }

	
    public Chitiethoadon(int maHd, int maPhong) {
        this.maHd = maHd;
        this.maPhong = maPhong;
    }
    public Chitiethoadon(int maHd, int maPhong, Integer soNgayThue, Float donGia, Date ngayTao) {
       this.maHd = maHd;
       this.maPhong = maPhong;
       this.soNgayThue = soNgayThue;
       this.donGia = donGia;
       this.ngayTao = ngayTao;
    }
   
    public Integer getMaCthd() {
        return this.maCthd;
    }
    
    public void setMaCthd(Integer maCthd) {
        this.maCthd = maCthd;
    }
    public int getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(int maHd) {
        this.maHd = maHd;
    }
    public int getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(int maPhong) {
        this.maPhong = maPhong;
    }
    public Integer getSoNgayThue() {
        return this.soNgayThue;
    }
    
    public void setSoNgayThue(Integer soNgayThue) {
        this.soNgayThue = soNgayThue;
    }
    public Float getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Float donGia) {
        this.donGia = donGia;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }




}


