package quanlykhachsan.entity;
// Generated Jun 1, 2019 12:10:57 AM by Hibernate Tools 4.3.1



/**
 * Loaikhach generated by hbm2java
 */
public class Loaikhach  implements java.io.Serializable {


     private int maLoai;
     private String tenLoai;
     private Double heSo;

    public Loaikhach() {
    }

	
    public Loaikhach(int maLoai, String tenLoai) {
        this.maLoai = maLoai;
        this.tenLoai = tenLoai;
    }
    public Loaikhach(int maLoai, String tenLoai, Double heSo) {
       this.maLoai = maLoai;
       this.tenLoai = tenLoai;
       this.heSo = heSo;
    }
   
    public int getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(int maLoai) {
        this.maLoai = maLoai;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Double getHeSo() {
        return this.heSo;
    }
    
    public void setHeSo(Double heSo) {
        this.heSo = heSo;
    }
     @Override
    public String toString()
    {
        return this.tenLoai;
    }


}


