package quanlykhachsan.entity;
// Generated Jun 1, 2019 12:10:57 AM by Hibernate Tools 4.3.1



/**
 * Phieuthuekhachhang generated by hbm2java
 */
public class Phieuthuekhachhang  implements java.io.Serializable {


     private Integer maPhieuThue;
     private String khachHang;
     private String loaiKhach;
     private String cmnd;
     private String diaChi;

    public Phieuthuekhachhang() {
    }

	
    public Phieuthuekhachhang(String khachHang, String loaiKhach, String cmnd) {
        this.khachHang = khachHang;
        this.loaiKhach = loaiKhach;
        this.cmnd = cmnd;
    }
    public Phieuthuekhachhang(String khachHang, String loaiKhach, String cmnd, String diaChi) {
       this.khachHang = khachHang;
       this.loaiKhach = loaiKhach;
       this.cmnd = cmnd;
       this.diaChi = diaChi;
    }
   
    public Integer getMaPhieuThue() {
        return this.maPhieuThue;
    }
    
    public void setMaPhieuThue(Integer maPhieuThue) {
        this.maPhieuThue = maPhieuThue;
    }
    public String getKhachHang() {
        return this.khachHang;
    }
    
    public void setKhachHang(String khachHang) {
        this.khachHang = khachHang;
    }
    public String getLoaiKhach() {
        return this.loaiKhach;
    }
    
    public void setLoaiKhach(String loaiKhach) {
        this.loaiKhach = loaiKhach;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }




}


