package quanlykhachsan.entity;
// Generated Jun 1, 2019 12:10:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieuthuephong generated by hbm2java
 */
public class Phieuthuephong  implements java.io.Serializable {


     private Integer maPhieuThue;
     private Date ngayThue;
     private Float tongTien;
     private int maHd;

    public Phieuthuephong() {
    }

	
    public Phieuthuephong(Date ngayThue, int maHd) {
        this.ngayThue = ngayThue;
        this.maHd = maHd;
    }
    public Phieuthuephong(Date ngayThue, Float tongTien, int maHd) {
       this.ngayThue = ngayThue;
       this.tongTien = tongTien;
       this.maHd = maHd;
    }
   
    public Integer getMaPhieuThue() {
        return this.maPhieuThue;
    }
    
    public void setMaPhieuThue(Integer maPhieuThue) {
        this.maPhieuThue = maPhieuThue;
    }
    public Date getNgayThue() {
        return this.ngayThue;
    }
    
    public void setNgayThue(Date ngayThue) {
        this.ngayThue = ngayThue;
    }
    public Float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Float tongTien) {
        this.tongTien = tongTien;
    }
    public int getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(int maHd) {
        this.maHd = maHd;
    }




}


