package quanlykhachsan.entity;
// Generated Jun 1, 2019 12:10:57 AM by Hibernate Tools 4.3.1



/**
 * Phong generated by hbm2java
 */
public class Phong  implements java.io.Serializable {


     private Integer maPhong;
     private String tenPhong;
     private String ghiChu;
     private String tinhTrang;
     private Integer maLoai;

    public Phong() {
    }

    public Phong(String tenPhong, String ghiChu, String tinhTrang, Integer maLoai) {
       this.tenPhong = tenPhong;
       this.ghiChu = ghiChu;
       this.tinhTrang = tinhTrang;
       this.maLoai = maLoai;
    }
   
    public Integer getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(Integer maPhong) {
        this.maPhong = maPhong;
    }
    public String getTenPhong() {
        return this.tenPhong;
    }
    
    public void setTenPhong(String tenPhong) {
        this.tenPhong = tenPhong;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Integer getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(Integer maLoai) {
        this.maLoai = maLoai;
    }




}


